### ISSUE TITLE
hi, how to build the project?

### ISSUE THREAD

**Issue by crazycode** [lixian/log-support-lite#1]
hi, 

how can i build the source for some change? I want add some feature, but I can't found any *.iml or build config.

can you add some description about build the project on readme?  thanks.

**Comment by lixian** [comment]
You are welcome to add features！

I updated the readme, as below.

## Development environment settings

For now, you can't _Open_ a new project without `.iml` and `.idea` as plugin project.
- File | New | Project... | IntelliJ Platform Plugin | Next
- Input the existing project name and location, and choose overwrite if there are
  config files existing.
